language: python
python:
  - "2.7"
install:
  - pip install -r test/requirements.txt --use-mirrors
before_script:
  - mysql -e 'create database sprks;'
script:
  - py.test
notifications:
  email: false
